// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace webNews.Domain.Entities
{
	[Alias("System_Option")]
    public partial class System_Option 
    {
        [Required]
        public int Id { get; set; }
        public string FooterText { get; set; }
        public string FooterImage { get; set; }
        public string Copyright { get; set; }
        public string Author { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyPhone { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyMap { get; set; }
        public string CompanyWebsite { get; set; }
    }

}
#pragma warning restore 1591
